import antfu from '@antfu/eslint-config'
import withNuxt from './.nuxt/eslint.config.mjs'

export default withNuxt(
  antfu({
    vue: true,
    typescript: true,
    // Generated by drizzle-kit — never hand-edited.
    ignores: ['server/database/migrations/**'],
  }),
  {
    files: ['pnpm-workspace.yaml'],
    rules: {
      // Wants trustPolicy: no-downgrade, which rejects this lockfile's semver@6.3.1.
      'pnpm/yaml-enforce-settings': 'off',
    },
  },
)
