import antfu from '@antfu/eslint-config'
import withNuxt from './.nuxt/eslint.config.mjs'

export default withNuxt(
  antfu({
    vue: true,
    typescript: true,
    ignores: [
      // Generated by drizzle-kit — never hand-edited.
      'server/database/migrations/**',
      // Code fences in the design docs are deliberately partial — object
      // literals on their own, `...` elisions, a single method body. They read
      // as prose, not as code that has to parse.
      'docs/**/*.md/**',
    ],
  }),
  {
    files: ['pnpm-workspace.yaml'],
    rules: {
      // Wants trustPolicy: no-downgrade, which rejects this lockfile's semver@6.3.1.
      'pnpm/yaml-enforce-settings': 'off',
    },
  },
)
